server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.28.37:3306/content_center?useUnicode=true
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root