server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.28.37:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace: 43c6e64f-436c-4bd0-8cc4-f858880583f9
        cluster-name: ChengDu
    # 配置属性的方式打印feign的日志
    sentinel:
      transport:
        # 指定sentinel控制台的地址
        dashboard: localhost:8080
  #    openfeign:
#      client:
#        config:
#          # 全局配置时将UserCenter改成default即可
#          UserCenter:
#            connect-timeout: 5000 # 连接超时时间
#            read-timeout: 5000 # 读取超时时间
#            logger-level: full
#            # error-decoder: com.xiwei.SimpleErrorDecoder 错误解码器
#            # retryer: com.xiwei.SimpleRetryer 重试策略
#            # request-interceptors:
#             # - com.xiwei.FooRequestInterceptor 拦截器
#            # contract: com.xiwei.SimpleContract 契约
#      httpclient:
#        # 让feign使用httpclient做请求而不是默认的URLConnection
#        enabled: true
#        # feign的最大连接数
#        max-connections: 200
#        # feign单个路径的最大连接数
#        max-connections-per-route: 50
  application:
    name: ContentCenter

logging:
  level:
    # com.xiwei: debug
    com.xiwei.contentcenter.feignclient.UserCenterFeignClient: debug
# 配置端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      # 显示详情，默认never
      show-details: always
      # 所有组件的详细信息，默认never
      show-components: always
      logging:
        slow-indicator-threshold: 1s
