server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.28.37:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace: 43c6e64f-436c-4bd0-8cc4-f858880583f9
        cluster-name: ChengDu
  application:
    name: ContentCenter